Protection/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('protector.urls'))
]

protector/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'protector'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('service/', views.service, name='services'),
    path('about/', views.about, name='about')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

protector/models.py
from django.db import models

# Create your models here.

class ClientsMessages(models.Model):
    name = models.CharField(max_length=20)
    phone = models.CharField(max_length=20)
    email = models.CharField(max_length=30)
    subject = models.CharField(max_length=50)
    message = models.TextField()
    

protector/forms.py
from django import forms
from . import models
from django.forms import TextInput, Textarea


class ClientsMessagesForm(forms.ModelForm):
    class Meta:
        model = models.ClientsMessages
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget = TextInput(
            attrs={
                'placeholder': 'Enter your name',
                'required': 'required',
            }
        )
        self.fields['phone'].widget = TextInput(
            attrs={
                'placeholder': 'Enter your contacts',
                'required': 'required',
            }
        )
        self.fields['email'].widget = TextInput(
            attrs={
                'placeholder': 'Enter your email',
                'required': 'required',
            }
        )
        self.fields['subject'].widget = TextInput(
            attrs={
                'placeholder': 'Enter your subject',
                'required': 'required',
            }
        )
        self.fields['message'].widget = Textarea(
            attrs={
                'placeholder': 'Enter your message',
                'required': 'required',
                'cols': 40,
                'rows':7
            }
        )

protector/views.py
from django.shortcuts import render, redirect
from .forms import ClientsMessagesForm

# Create your views here.


def index(request):
    if request.method == 'POST':
        form = ClientsMessagesForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('protector:index')
    else:
        form = ClientsMessagesForm()
    return render(request, 'index.html',{'form':form})


def contact(request):
    if request.method == 'POST':
        form = ClientsMessagesForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('protector:index')
    else:
        form = ClientsMessagesForm()
    return render(request, 'contact.html',{'form':form})


def service(request):
    return render(request, 'service.html')


def about(request):
    return render(request, 'about.html')

protector/templates/contact.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- Medipro CSS -->
<link rel="stylesheet" href="{% static 'addition/css/normalize.css' %}">

<!-- Breadcrumbs -->
<div class="breadcrumbs overlay">
	<div class="container">
		<div class="bread-inner">
			<div class="row">
				<div class="col-12">
					<h2>Contact Us</h2>
					<ul class="bread-list">
						<li><a href="{% url 'protector:index' %}">Home</a></li>
						<li><i class="icofont-simple-right"></i></li>
						<li class="active">Contact Us</li>
					</ul>
				</div>
			</div>
		</div>
	</div>
</div>
<!-- End Breadcrumbs -->

<!-- Start Contact Us -->
<section class="contact-us section">
	<div class="container">
		<div class="inner">
			<div class="row">
				<div class="col-lg-6" style="background-color: ghostwhite">
					<div class="container">
						<div class="container">
							<br>
							<h6 style="color: rgb(0, 0, 0);">Your security journey begins here</h6>
						</div>
						<br>
						<div class="container">
							<h2 style="color: red;">Talk to Us</h2>
							<br>
							<h5>Location</h5>
							<br>
							<p style="margin-left: 10px;"><i style="color:blue" class="icofont-google-map"></i>Office
								PD46 M- Floor MD39 <br>
								<spanc style="margin-left: 10px;">Gweru Main Post Office
									Building Gweru</span>
							</p>
							<br>
							<h5>Email Us</h5>
							<br>
							<p style="margin-left: 10px;"><i style="color:blue" class="fa fa-envelope"></i> <a
									href="mailto:shieldguardzim@gmail.com">shieldguardzim@gmail.com</a>
							</p>
							<br>
							<h5>Call Us</h5>
							<br>
							<p style="margin-left: 10px;"><i style="color: blue;" class="icofont icofont-ui-call"></i><a
									href="tel:+26354222391">+26354222391</a></p>
						</div>
					</div>

				</div>
				<br>
				<br>
				<br>
				<div class="col-lg-6">
					<div class="contact-us-form">
						<h2 style="color:red">Contact With Us</h2>
						<p>If you have any questions please fell free to contact with us.</p>
						<!-- Form -->
						<form class="form" method="post" action="{% url 'protector:contact' %}"
							enctype="multipart/form-data">
							{% csrf_token %}
							<div class="row">
								<div class="col-lg-6">
									<div class="form-group">
										{{form.name}}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										{{form.email}}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										{{form.phone}}
									</div>
								</div>
								<div class="col-lg-6">
									<div class="form-group">
										{{form.subject}}
									</div>
								</div>
								<div class="col-lg-12">
									<div class="form-group">
										{{form.message}}
									</div>
								</div>
								<div class="col-12">
									<div class="form-group login-btn">
										<button class="btn" type="submit">Send</button>
									</div>
								</div>
							</div>
						</form>
						<!--/ End Form -->
					</div>
				</div>
			</div>
		</div>
		<div class="contact-info">
			<div class="row">
				<!-- single-info -->
				<div class="col-lg-4 col-12 ">
					<div class="single-info">
						<i class="icofont icofont-ui-call"></i>
						<div class="content">
							<h3> <a href="tel:+26354222391">+26354222391</a></h3>
							<p> <a href="mailto:shieldguardzim@gmail.com">shieldguardzim@gmail.com</a></p>
						</div>
					</div>
				</div>
				<!--/End single-info -->
				<!-- single-info -->
				<div class="col-lg-4 col-12 ">
					<div class="single-info">
						<i class="icofont-google-map"></i>
						<div class="content">
							<h3>Address</h3>
							<p>Office PD46 M- Floor MD39 Gweru Main Post Office Building Gweru</p>
						</div>
					</div>
				</div>
				<!--/End single-info -->
				<!-- single-info -->
				<div class="col-lg-4 col-12 ">
					<div class="single-info">
						<i class="icofont icofont-wall-clock"></i>
						<div class="content">
							<h3>Mon - Sun: 24/7</h3>
							<p>Every Day</p>
						</div>
					</div>
				</div>
				<!--/End single-info -->
			</div>
		</div>
	</div>
</section>
<!--/ End Contact Us -->

</body>

</html>

<!-- end contact section -->

{% endblock %}

protector/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block content %}

<!-- slider section -->
<section class=" slider_section">
  <div id="carouselExampleIndicators" class="carousel slide vert" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <div class="slider_box">
          <div class="fixed_company-detail">
            <p>
              Sh1eldGuard Company
            </p>
          </div>
          <div class="slider-detail">
            <div class="slider_detail-heading">
              <h2>
                We are ShieldGuard
              </h2>
              <h1 style="color: red;">
                Our Approach
              </h1>
            </div>
            <div class="slider_detail-text">
              <p style="color: rgb(50, 11, 224); font-weight: bold; font-size: larger;">
                “Working in Partnership” - The success of our business relies on the
                philosophy of treating customers as our business partners.

              </p>
            </div>
            <div class="slider_detail-btn">
              <a href="{% url 'protector:about' %}">
                <span>
                  Read More
                </span>
                <img src="../static/images/arrow.png" alt="" class="ml-2" />
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="slider_boxx">
          <div class="fixed_company-detail">
            <p>
              Sh1eldGuard Company
            </p>
          </div>
          <div class="slider-detail">
            <div class="slider_detail-heading">
              <h2>
                We are ShieldGuard
              </h2>
              <h1 style="color: red">
                Our Belief
              </h1>
            </div>
            <div class="slider_detail-text">
              <p style="color: rgb(50, 11, 224); font-weight: bold; font-size: larger;">
                “Based on a strong foundation of dependable service and reasonable pricing, Shieldguard offers
                something unique extra that simply cannot be matched in the market we operate.”
              </p>
            </div>
            <div class="slider_detail-btn">
              <a href="{% url 'protector:about' %}">
                <span>
                  Read More
                </span>
                <img src="../static/images/arrow.png" alt="" class="ml-2" />
              </a>
            </div>
          </div>
        </div>
      </div>
      <div class="carousel-item">
        <div class="slider_boxxx">
          <div class="fixed_company-detail">
            <p>
              Sh1eldGuard Company
            </p>
          </div>
          <div class="slider-detail">
            <div class="slider_detail-heading">
              <h2>
                We are ShieldGuard
              </h2>
              <h1 style="color: red">
                Our Vision
              </h1>
            </div>
            <div class="slider_detail-text">
              <p style="color: rgb(50, 11, 224); font-weight: bold; font-size: larger;">
                To be a market leader in the provision of security and related services in Zimbabwe by the year 2050.
              </p>
            </div>
            <div class="slider_detail-btn">
              <a href="{% url 'protector:about' %}">
                <span>
                  Read More
                </span>
                <img src="../static/images/arrow.png" alt="" class="ml-2" />
              </a>
            </div>
          </div>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</section>

<!-- end slider section -->

<!-- welcome section -->
<section class="welcome_section layout_padding">
  <div class="container-fluid">
    <div class="row">
      <div class=" col-md-6">
        <div>
          <img class="img-fluid" src="../static/images/welcome.jpg" alt="" />
        </div>
      </div>
      <div class=" col-md-6">
        <div class="welcome_detail">
          <h3>
            Welcome
          </h3>
          <h2>
            We Achieve best results for Our Customers
          </h2>
          <p>
            We work together as a team, valuing everyone’s contribution, to ensure that we
            achieve the best results for our customers and our business. We pride ourselves on the value we
            offer our stakeholders through engaged employees, cost containment, operational excellence,
            customer centricity, and profitable revenue growth. Utilizing these strategic levers to drive
            increased value in our safety and security processes is what has placed us above the rest.
          </p>
          <div class="welcome_detail-btn">
            <a href="{% url 'protector:about' %}">
              <span>
                Read More
              </span>
              <img src="../static/images/arrow-black.png" alt="" class="ml-2" />
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- end welcome section -->

<!-- service section -->
<section class="service_section ">
  <div class="container">
    <div class="service_detail">
      <h3>
        We
      </h3>
      <h2>
        we provide service
      </h2>
    </div>
    <div class="service_img-container">
      <!-- <div class="service_img-box i-box-1">
          <a href=""> Bank security</a>
        </div>
        <div class="service_img-box i-box-2">
          <a href="">society Guard </a>
        </div> -->
      <div class="service_img-box i-box-3">
        <a href="{% url 'protector:about' %}">Hotel Security </a>
      </div>
      <div class="service_img-box i-box-4">
        <a href="{% url 'protector:about' %}"> Home security</a>
      </div>
    </div>
    <div class="service_btn">
      <a href="{% url 'protector:about' %}">
        <span>
          Read More
        </span>
        <img src="../static/images/arrow-black.png" alt="" class="ml-2" />
      </a>
    </div>
  </div>
</section>
<!-- end service section -->

<!-- security section -->

<section class="security_section layout_padding">
  <h3>
    Security

  </h3>
  <h2 style="color: red;">
    Our Guards
  </h2>
  <div class="security_container">
    <div class="carousel-wrap">
      <div class="owl-carousel">
        <div class="item">
          <div class="security_img-box i-box-1">
            <!-- <a href=""> View More</a> -->
          </div>
        </div>
        <div class="item">
          <div class="security_img-box i-box-2">
            <!-- <a href=""> View More</a> -->
          </div>
        </div>
        <div class="item">
          <div class="security_img-box i-box-3">
            <!-- <a href=""> View More</a> -->
          </div>
        </div>

      </div>
    </div>
  </div>
</section>
<hr>
<hr>
<!-- end security section -->

<!-- story section -->

<!-- <section class="layout_padding story_section">
  <div class="container-fluid">
    <div class="row">
      <div class=" col-md-6">
        <div>
          <img class="img-fluid" src="../static/images/security.jpg" alt="" />
        </div>
      </div>
      <div class=" col-md-6">
        <div class="story_detail">
          <h3>
          </h3>
          <h2>
            Our Value Statement
          </h2>
          <p>
            We act with integrity and respect. Our business activities and relationships are built on trust,
            honesty, and openness. We do what we promise and always strive to do the right thing. We
            listen. We treat our colleagues, customers, and those in our care with the utmost respect.
            We are passionate about safety, security, and service excellence. We are passionate about
            working safely and take great care to protect our colleagues from harm. We are experts in
            security and use that knowledge to protect our customers’ assets. We keep our promises and
            are passionate about delivering high levels of customer service.
            We achieve this through innovation. We invest in technology and best practices to continuously
            improve our products and service. We challenge ourselves to find new ways of helping
            customers achieve their goals.
          </p>
          <div class="story_detail-btn">
            <a href="{% url 'protector:about' %}">
              <span>
                Read More
              </span>
              <img src="../static/images/arrow-black.png" alt="" class="ml-2" />
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
</section> -->

<!-- end story section -->

<!-- contact section -->
<section class="contact_section layout_padding-top">
  <div class="container-fluid">
    <div class="row">
      <div class=" col-md-6 contact_form-container">
        <div class="contact_box">
          <form class="form" method="post" action="{% url 'protector:index' %}" enctype="multipart/form-data">
            {% csrf_token %}
            <!-- <input type="text" placeholder="Your Name"> -->
            {{form.name}}
            <!-- <input type="email" placeholder="Email"> -->
            {{form.email}}
            <!-- <input type="text" placeholder="Phone Number"> -->
            {{form.phone}}
            <!-- <input type="text" placeholder="Message"> -->
            {{form.subject}}
            <br>
            {{form.message}}

            <div>
              <button type="submit">
                Submit
              </button>
            </div>
          </form>
        </div>
      </div>

      <div class=" col-md-6">
        <div class="story_detail">
          <h2 style="color: red;">
            Our Value Statement
          </h2>
          <br>
          <p style="text-align: justify;">
            We act with integrity and respect. Our business activities and relationships are built on trust,
            honesty, and openness. We do what we promise and always strive to do the right thing. We
            listen. We treat our colleagues, customers, and those in our care with the utmost respect.
            We are passionate about safety, security, and service excellence. <br> <br> We are passionate about
            working safely and take great care to protect our colleagues from harm. We are experts in
            security and use that knowledge to protect our customers’ assets. We keep our promises and
            are passionate about delivering high levels of customer service.
            We achieve this through innovation. We invest in technology and best practices to continuously
            improve our products and service. We challenge ourselves to find new ways of helping
            customers achieve their goals.
          </p>
          <div class="story_detail-btn">
            <a href="{% url 'protector:about' %}">
              <span>
                Read More
              </span>
              <img src="../static/images/arrow-black.png" alt="" class="ml-2" />
            </a>
          </div>
        </div>
      </div>
    </div>
  </div>
  <p>.</p>
  <br>
  </div>
</section>

<!-- end contact section -->

{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <!-- Basic -->
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <!-- Mobile Metas -->
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <!-- Site Metas -->
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>ShieldGuard</title>
    		<!-- Favicon -->
        <link rel="icon" href="img/favicon.png">
		<!-- Google Fonts -->
		<link href="https://fonts.googleapis.com/css?family=Poppins:200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i&display=swap" rel="stylesheet">

		<!-- Bootstrap CSS -->
		<link rel="stylesheet" href="{% static 'addition/css/bootstrap.min.css' %}">
		<!-- Nice Select CSS -->
		<link rel="stylesheet" href="{% static 'addition/css/nice-select.css' %}">
		<!-- Font Awesome CSS -->
        <link rel="stylesheet" href="{% static 'addition/css/font-awesome.min.css' %}">
		<!-- icofont CSS -->
        <link rel="stylesheet" href="{% static 'addition/css/icofont.css' %}">
		<!-- Slicknav -->
		<link rel="stylesheet" href="{% static 'addition/css/slicknav.min.css' %}">
		<!-- Owl Carousel CSS -->
        <link rel="stylesheet" href="{% static 'addition/css/owl-carousel.css' %}">
		<!-- Datepicker CSS -->
		<link rel="stylesheet" href="{% static 'addition/css/datepicker.css' %}">
		<!-- Animate CSS -->
        <link rel="stylesheet" href="{% static 'addition/css/animate.min.css' %}">
		<!-- Magnific Popup CSS -->
        <link rel="stylesheet" href="{% static 'addition/css/magnific-popup.css' %}">
		
		<!-- Medipro CSS -->
    
        <link rel="stylesheet" href="{% static 'addition/css/normalize.css' %}">
        <link rel="stylesheet" href="{% static 'style/style.css' %}">
        <link rel="stylesheet" href="{% static 'addition/css/responsive.css' %}">
		
    <!-- slider stylesheet -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/owl.carousel.min.css' %}"
    />

    <!-- bootstrap core css -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/bootstrap.css' %}"
    />

    <!-- fonts style -->
    <link href="{% static 'css/css.css' %}" rel="stylesheet" />
    <!-- Custom styles for this template -->
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <!-- responsive style -->
    <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
  </head>

  <body>
    <!-- header section strats -->

		<!-- Header Area -->
		<header class="header" >
			<!-- Topbar -->
			<div class="topbar">
				<div class="container">
					<div class="row">
						<div class="col-lg-6 col-md-5 col-12">
							<!-- Contact -->
              <a href="" ><span style="background-color: blue;padding: 8px;" ><img src="../static/images/fb.png" alt="" /></span></a>
              <a href=""><span style="background-color: blue; padding: 8px;" ><img src="../static/images/twitter.png" alt="" /></span></a>
                  

              

							<!-- <ul class="top-link">
								<li><a href="#">About</a></li>
								<li><a href="#">Doctors</a></li>
								<li><a href="#">Contact</a></li>
								<li><a href="#">FAQ</a></li>
							</ul> -->
							<!-- End Contact -->
						</div>
						<div class="col-lg-6 col-md-7 col-12">
							<!-- Top Contact -->
							<ul class="top-contact">
								<li><i class="fa fa-phone" ><a href="tel:+26354222391">+26354222391</a></i ></li>
								<li><i class="fa fa-envelope"></i><a href="mailto:shieldguardzim@gmail.com
">shieldguardzim@gmail.com
</a></li>
							</ul>
							<!-- End Top Contact -->
						</div>
					</div>
				</div>
			</div>
      </header>
			<!-- End Topbar -->
    <header class="header_section">
      <div class="container">
        <nav class="navbar navbar-expand-lg custom_nav-container">
          <a class="navbar-brand" href="#">
            <div class="logo_box">
              <img src="../static/images/logo.png" alt="" />
            </div>
          </a>
          <button
            class="navbar-toggler"
            type="button"
            data-toggle="collapse"
            data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto mr-2">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'protector:index' %}"
                  >Home <span class="sr-only">(current)</span></a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'protector:about' %}"
                  >About Us
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'protector:services' %}"
                  >Services</a
                >
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'protector:contact' %}"
                  >Contact us</a
                >
              </li>
            </ul>
          </div>
        </nav>
      </div>
    </header>
    <!-- end header section -->

    {% block content %} {% endblock %}

    <!-- info section -->
    <section class="info_section layout_padding">
      <div class="container">
        <div class="row">
          <div class="col-md-4 ">
            <div style="margin-left: 24px;"> 
              <h4 style="color: red;">Our History</h4>
              <br>
              <p style="text-align: justify; color: white;">
                Shieldguard Security was established and incorporated in 2021 as
                a specialized security services company to provide high-level,
                professional, effective, and efficient security guard services
                across a broad spectrum of organizations in Zimbabwe.
              </p>
            </div>
          </div>  
          <div class="col-md-4 address_container">
            <div>
              <h4 style="color: red;margin-left: 24px;"> Address:</h4>
              <div class="address_link-container" style="margin-left: 0px;">
                <a href="">
                  <img src="../static/images/location.png" alt="" />
                  <span style="color: white;"> Office PD46 M- Floor MD39
Gweru Main Post Office
Building Gweru
 </span>
                </a>
                <a href="tel:+26354222391">
                  <img src="../static/images/phone.png" alt="" />
                  <span style="color: white;"> Tel: +26354222391 </span>
                </a>
                <a href="mailto:shieldguardzim@gmail.com">
                  <img src="../static/images/mail.png" alt="" />
                  <span style="color: white;"> Email: shieldguardzim@gmail.com
 </span>
                </a>
              </div>
            </div>
          </div>
          <div class="col-md-4 news_container">
            <div style="margin-left: 24px;">
              <div>
                <h4 style="color: red;">Quick Links</h4>
              </div>


									
                    <div class="single-footer f-link"></div>
										  <ul>
                        <li style="color: white; margin-left: 10px;"><a href="{% url 'protector:index' %}"><i class="fa fa-caret-right" aria-hidden="true"></i>Home</a></li>
                        <li style="color: white; margin-left: 10px;"><a href="{% url 'protector:about' %}"><i class="fa fa-caret-right" aria-hidden="true"></i>About Us</a></li>
                        <li style="color: white; margin-left: 10px;"><a href="{% url 'protector:services' %}"><i class="fa fa-caret-right" aria-hidden="true"></i>Services</a></li>
                        <li style="color: white; margin-left: 10px;"><a href="{% url 'protector:contact' %}"><i class="fa fa-caret-right" aria-hidden="true"></i>Contact Us</a></li>	
                      </ul>
									  </div>



                    <br>
              <div class="social_container">
                <div>
                  <img src="../static/images/fb.png" alt="" />
                </div>
                <div>
                  <img src="../static/images/twitter.png" alt="" />
                </div>
                <div>
                  <img src="../static/images/linkedin.png" alt="" />
                </div>
                <div>
                  <img src="../static/images/youtube.png" alt="" />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- end info section -->

    <!-- footer section -->
    <section class="container-fluid footer_section">
      <p>
        Copyright &copy; 2024 All Rights Reserved By
        ShieldGuard
      </p>
    </section>
    <!-- footer section -->

    <script
      type="text/javascript"
      src="{% static 'js/jquery-3.4.1.min.js' %}"
    ></script>
    <script
      type="text/javascript"
      src="{% static 'js/bootstrap.js' %}"
    ></script>
    <script
      type="text/javascript"
      src="{% static 'js/owl.carousel.min.js' %}"
    ></script>
    <script type="text/javascript">
      $(".owl-carousel").owlCarousel({
        loop: true,
        margin: 20,
        nav: true,
        navText: [],
        autoplay: true,
        autoplayHoverPause: true,
        responsive: {
          0: {
            items: 1,
          },
          600: {
            items: 2,
          },
          1000: {
            items: 3,
          },
        },
      });
    </script>

    <script>
      $(".nav_search-btn").click(function () {
        if ($(".nav_search-input").hasClass("d-none")) {
          event.preventDefault();
          $(".nav_search-input")
            .animate(
              {
                left: "-1000px",
              },
              "1000000"
            )
            .removeClass("d-none");
        } else {
          $(".nav_search-input")
            .animate(
              {
                left: "0px",
              },
              "1000000"
            )
            .addClass("d-none");
        }
      });
    </script>

    <script>
      // This example adds a marker to indicate the position of Bondi Beach in Sydney,
      // Australia.
      function initMap() {
        var map = new google.maps.Map(document.getElementById("map"), {
          zoom: 11,
          center: {
            lat: 40.645037,
            lng: -73.880224,
          },
        });

        var image = "images/maps-and-flags.png";
        var beachMarker = new google.maps.Marker({
          position: {
            lat: 40.645037,
            lng: -73.880224,
          },
          map: map,
          icon: image,
        });
      }
    </script>
    <!-- google map js -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA8eaHt9Dh5H57Zh0xVTqxVdBFCvFMqFjQ&callback=initMap"></script>
    <!-- end google map js -->
  </body>
</html>

templates/navbar.html
	
    
    
    
    
    
    
    
    
    
    
    
    
    <div class="topbar">
				<div class="container">
					<div class="row">
						<div class="col-lg-6 col-md-5 col-12">
							<!-- Contact -->
							<ul class="top-link">
								<li><a href="#">About</a></li>
								<li><a href="#">Doctors</a></li>
								<li><a href="#">Contact</a></li>
								<li><a href="#">FAQ</a></li>
							</ul>
							<!-- End Contact -->
						</div>
						<div class="col-lg-6 col-md-7 col-12">
							<!-- Top Contact -->
							<ul class="top-contact">
								<li><i class="fa fa-phone"></i>+880 1234 56789</li>
								<li><i class="fa fa-envelope"></i><a href="mailto:support@yourmail.com">support@yourmail.com</a></li>
							</ul>
							<!-- End Top Contact -->
						</div>
					</div>
				</div>
			</div>